-- =========================================================
-- 000 — Esquema completo de BarrioFix
--
-- Es el DDL que ya esta aplicado en la instancia RDS. Vive aca para que el
-- esquema sea reproducible: sin esto, la unica copia de la estructura de la
-- base esta dentro de la instancia y no hay forma de recrearla.
--
-- Correr en orden: 000 -> 001 -> 002 -> 003
-- =========================================================


-- =========================================================
-- 1. CUENTA
-- =========================================================

CREATE TABLE IF NOT EXISTS cuenta (
    id_cuenta BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_cuenta PRIMARY KEY (id_cuenta),
    CONSTRAINT uq_cuenta_username UNIQUE (username)
);


-- =========================================================
-- 2. USUARIO — relacion 1:1 con CUENTA via id_cuenta UNIQUE
-- =========================================================

CREATE TABLE IF NOT EXISTS usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_cuenta BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefono VARCHAR(30),
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),

    CONSTRAINT fk_usuario_cuenta
        FOREIGN KEY (id_cuenta)
        REFERENCES cuenta(id_cuenta)
        ON DELETE RESTRICT,

    CONSTRAINT uq_usuario_cuenta UNIQUE (id_cuenta),
    CONSTRAINT uq_usuario_email UNIQUE (email)
);


-- =========================================================
-- 3. CLIENTE — subtipo de USUARIO
-- =========================================================

CREATE TABLE IF NOT EXISTS cliente (
    id_usuario BIGINT NOT NULL,

    CONSTRAINT pk_cliente PRIMARY KEY (id_usuario),

    CONSTRAINT fk_cliente_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
        ON DELETE CASCADE
);


-- =========================================================
-- 4. PROFESIONAL — subtipo de USUARIO
-- =========================================================

CREATE TABLE IF NOT EXISTS profesional (
    id_usuario BIGINT NOT NULL,
    descripcion TEXT,
    disponible BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_profesional PRIMARY KEY (id_usuario),

    CONSTRAINT fk_profesional_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
        ON DELETE CASCADE
);


-- =========================================================
-- 5. CATEGORIA
-- =========================================================

CREATE TABLE IF NOT EXISTS categoria (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_categoria PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categoria_nombre UNIQUE (nombre)
);


-- =========================================================
-- 6. PROFESIONAL_CATEGORIA — resuelve el N:M
-- =========================================================

CREATE TABLE IF NOT EXISTS profesional_categoria (
    id_profesional BIGINT NOT NULL,
    id_categoria BIGINT NOT NULL,

    CONSTRAINT pk_profesional_categoria
        PRIMARY KEY (id_profesional, id_categoria),

    CONSTRAINT fk_prof_categoria_profesional
        FOREIGN KEY (id_profesional)
        REFERENCES profesional(id_usuario)
        ON DELETE CASCADE,

    CONSTRAINT fk_prof_categoria_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria(id_categoria)
        ON DELETE CASCADE
);


-- =========================================================
-- 7. ZONA — pertenece a la SOLICITUD, no al profesional
-- =========================================================

CREATE TABLE IF NOT EXISTS zona (
    id_zona BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_zona PRIMARY KEY (id_zona),
    CONSTRAINT uq_zona_nombre UNIQUE (nombre)
);


-- =========================================================
-- 8. URGENCIA
-- =========================================================

CREATE TABLE IF NOT EXISTS urgencia (
    id_urgencia BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    orden_prioridad SMALLINT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_urgencia PRIMARY KEY (id_urgencia),
    CONSTRAINT uq_urgencia_nombre UNIQUE (nombre),
    CONSTRAINT uq_urgencia_orden UNIQUE (orden_prioridad),

    CONSTRAINT ck_urgencia_orden
        CHECK (orden_prioridad > 0)
);


-- =========================================================
-- 9. ESTADO
-- =========================================================

CREATE TABLE IF NOT EXISTS estado (
    id_estado BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    descripcion TEXT,
    es_inicial BOOLEAN NOT NULL DEFAULT FALSE,
    es_final BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_estado PRIMARY KEY (id_estado),
    CONSTRAINT uq_estado_nombre UNIQUE (nombre),

    CONSTRAINT ck_estado_inicial_final
        CHECK (NOT (es_inicial AND es_final))
);


-- Solo puede existir UN estado marcado como inicial.
CREATE UNIQUE INDEX IF NOT EXISTS uq_estado_unico_inicial
ON estado (es_inicial)
WHERE es_inicial = TRUE;


-- =========================================================
-- 10. SOLICITUD
--
-- No guarda estado_actual ni profesional_actual: los dos salen de
-- SEGUIMIENTO_SOLICITUD.
-- =========================================================

CREATE TABLE IF NOT EXISTS solicitud (
    id_solicitud BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente BIGINT NOT NULL,
    id_categoria BIGINT NOT NULL,
    id_urgencia BIGINT NOT NULL,
    id_zona BIGINT NOT NULL,

    titulo VARCHAR(150) NOT NULL,
    descripcion TEXT NOT NULL,
    direccion VARCHAR(255) NOT NULL,

    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    cancelada_por_cliente BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_cancelacion_cliente TIMESTAMPTZ,

    CONSTRAINT pk_solicitud PRIMARY KEY (id_solicitud),

    CONSTRAINT fk_solicitud_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_usuario)
        ON DELETE RESTRICT,

    CONSTRAINT fk_solicitud_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria(id_categoria)
        ON DELETE RESTRICT,

    CONSTRAINT fk_solicitud_urgencia
        FOREIGN KEY (id_urgencia)
        REFERENCES urgencia(id_urgencia)
        ON DELETE RESTRICT,

    CONSTRAINT fk_solicitud_zona
        FOREIGN KEY (id_zona)
        REFERENCES zona(id_zona)
        ON DELETE RESTRICT,

    -- El flag y la fecha van siempre juntos.
    CONSTRAINT ck_solicitud_cancelacion
        CHECK (
            (cancelada_por_cliente = FALSE
             AND fecha_cancelacion_cliente IS NULL)
            OR
            (cancelada_por_cliente = TRUE
             AND fecha_cancelacion_cliente IS NOT NULL)
        ),

    CONSTRAINT ck_solicitud_fecha_cancelacion
        CHECK (
            fecha_cancelacion_cliente IS NULL
            OR fecha_cancelacion_cliente >= fecha_creacion
        )
);


-- =========================================================
-- 11. SEGUIMIENTO_SOLICITUD
--
-- La fila con fecha_hasta NULL es el estado actual.
-- =========================================================

CREATE TABLE IF NOT EXISTS seguimiento_solicitud (
    id_seguimiento BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_solicitud BIGINT NOT NULL,
    id_estado BIGINT NOT NULL,

    id_profesional BIGINT,
    id_usuario_actor BIGINT,

    fecha_desde TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_hasta TIMESTAMPTZ,

    motivo TEXT,

    CONSTRAINT pk_seguimiento PRIMARY KEY (id_seguimiento),

    CONSTRAINT fk_seguimiento_solicitud
        FOREIGN KEY (id_solicitud)
        REFERENCES solicitud(id_solicitud)
        ON DELETE CASCADE,

    CONSTRAINT fk_seguimiento_estado
        FOREIGN KEY (id_estado)
        REFERENCES estado(id_estado)
        ON DELETE RESTRICT,

    CONSTRAINT fk_seguimiento_profesional
        FOREIGN KEY (id_profesional)
        REFERENCES profesional(id_usuario)
        ON DELETE RESTRICT,

    CONSTRAINT fk_seguimiento_actor
        FOREIGN KEY (id_usuario_actor)
        REFERENCES usuario(id_usuario)
        ON DELETE SET NULL,

    CONSTRAINT ck_seguimiento_fechas
        CHECK (
            fecha_hasta IS NULL
            OR fecha_hasta > fecha_desde
        )
);


-- Solo puede existir UNA situacion actual por solicitud.
-- Este indice es lo que impide que dos profesionales tomen el mismo trabajo.
CREATE UNIQUE INDEX IF NOT EXISTS uq_seguimiento_actual_solicitud
ON seguimiento_solicitud (id_solicitud)
WHERE fecha_hasta IS NULL;


-- =========================================================
-- 12. FOTO_SOLICITUD — el archivo real vive en S3
-- =========================================================

CREATE TABLE IF NOT EXISTS foto_solicitud (
    id_foto BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_solicitud BIGINT NOT NULL,
    id_usuario_carga BIGINT NOT NULL,

    tipo_foto VARCHAR(10) NOT NULL,

    s3_key VARCHAR(1024) NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,

    fecha_subida TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    descripcion TEXT,

    CONSTRAINT pk_foto_solicitud PRIMARY KEY (id_foto),

    CONSTRAINT fk_foto_solicitud
        FOREIGN KEY (id_solicitud)
        REFERENCES solicitud(id_solicitud)
        ON DELETE CASCADE,

    CONSTRAINT fk_foto_usuario
        FOREIGN KEY (id_usuario_carga)
        REFERENCES usuario(id_usuario)
        ON DELETE RESTRICT,

    CONSTRAINT uq_foto_s3_key UNIQUE (s3_key),

    CONSTRAINT ck_foto_tipo
        CHECK (tipo_foto IN ('ANTES', 'DESPUES', 'OTRA'))
);


-- =========================================================
-- 13. CALIFICACION
--
-- No guarda id_cliente ni id_profesional: salen de SOLICITUD + SEGUIMIENTO.
-- =========================================================

CREATE TABLE IF NOT EXISTS calificacion (
    id_calificacion BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_solicitud BIGINT NOT NULL,

    puntuacion SMALLINT NOT NULL,
    comentario TEXT,
    fecha_calificacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_calificacion PRIMARY KEY (id_calificacion),

    CONSTRAINT fk_calificacion_solicitud
        FOREIGN KEY (id_solicitud)
        REFERENCES solicitud(id_solicitud)
        ON DELETE CASCADE,

    -- Una solicitud recibe como maximo una calificacion.
    CONSTRAINT uq_calificacion_solicitud UNIQUE (id_solicitud),

    CONSTRAINT ck_calificacion_puntuacion
        CHECK (puntuacion BETWEEN 1 AND 5)
);
