-- =========================================================
-- 002 — Catalogos base
--
-- Idempotente: se puede correr de nuevo sin duplicar nada.
-- =========================================================

INSERT INTO estado (nombre, descripcion, es_inicial, es_final) VALUES
    ('PENDIENTE',   'Solicitud publicada y disponible para profesionales', TRUE,  FALSE),
    ('ASIGNADO',    'Solicitud aceptada por un profesional',               FALSE, FALSE),
    ('EN_PROGRESO', 'El profesional esta realizando el trabajo',           FALSE, FALSE),
    ('RESUELTO',    'Trabajo finalizado',                                  FALSE, TRUE),
    ('CANCELADO',   'El cliente ha cancelado la solicitud',                FALSE, TRUE)
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO urgencia (nombre, orden_prioridad) VALUES
    ('BAJA', 1),
    ('MEDIA', 2),
    ('ALTA', 3)
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO categoria (nombre, descripcion, activo) VALUES
('Plomería', 'Instalación y reparación de cañerías, destapaciones, grifería, calefones y termotanques', TRUE),
('Electricidad', 'Instalaciones eléctricas, reparación de cortocircuitos, tableros y luminarias', TRUE),
('Gas', 'Instalación y reparación de artefactos a gas, detección de fugas por matriculados', TRUE),
('Aire acondicionado y climatización', 'Instalación, carga de gas, service y reparación de equipos de climatización y calefacción', TRUE),
('Cerrajería', 'Apertura de puertas, cambio de cerraduras y copias de llaves', TRUE),
('Albañilería', 'Arreglos generales de construcción, revoques y reparación de humedad', TRUE),
('Pintura', 'Pintura de interiores, exteriores y empapelado', TRUE),
('Yesería y durlock', 'Construcción y reparación de cielorrasos y tabiques en durlock', TRUE),
('Colocación de pisos y cerámicos', 'Instalación y reparación de pisos, cerámicos y porcelanato', TRUE),
('Impermeabilización de techos', 'Tratamiento e impermeabilización de techos y superficies', TRUE),
('Herrería', 'Fabricación y reparación de rejas, portones y estructuras metálicas', TRUE),
('Carpintería', 'Fabricación y reparación de muebles, puertas, ventanas y aberturas de madera', TRUE),
('Vidriería', 'Colocación y reparación de vidrios, espejos y mamparas', TRUE),
('Reparación de electrodomésticos', 'Service y reparación de heladeras, lavarropas, hornos y microondas', TRUE),
('Técnico en computación y redes', 'Reparación de PC, configuración de redes wifi e instalación de cámaras de seguridad', TRUE),
('Instalación de TV y home theater', 'Montaje y configuración de televisores y equipos de audio/video', TRUE),
('Domótica y hogar inteligente', 'Instalación y configuración de dispositivos inteligentes para el hogar', TRUE),
('Limpieza del hogar', 'Limpieza general, profunda y post obra de viviendas', TRUE),
('Limpieza de tapizados y alfombras', 'Limpieza profunda de sillones, colchones y alfombras', TRUE),
('Limpieza de vidrios y fachadas', 'Limpieza de vidrios, ventanales y fachadas de edificios', TRUE),
('Fumigación y control de plagas', 'Servicios de desinfección y control de plagas domiciliarias', TRUE),
('Jardinería y paisajismo', 'Mantenimiento de jardines, poda y diseño de espacios verdes', TRUE),
('Piscinas', 'Mantenimiento, limpieza y reparación de piscinas', TRUE),
('Techista', 'Reparación de techos, canaletas y desagües pluviales', TRUE),
('Tratamiento de humedad', 'Diagnóstico y solución de problemas de humedad en paredes y techos', TRUE),
('Antenista', 'Instalación y reparación de antenas de televisión y satelitales', TRUE),
('Mudanzas y fletes', 'Servicio de mudanzas, transporte de muebles y fletes en general', TRUE),
('Armado de muebles', 'Armado y montaje de muebles nuevos', TRUE),
('Colocación de cortinas y cuadros', 'Instalación de cortinas, cuadros, estanterías y objetos de decoración', TRUE),
('Instalación de alarmas y cámaras', 'Instalación de sistemas de seguridad, alarmas y videovigilancia', TRUE),
('Tapicería', 'Reparación y renovación de tapizados de sillones y muebles', TRUE),
('Afilado de herramientas', 'Afilado de cuchillos, tijeras y herramientas de corte', TRUE),
('Decoración de interiores', 'Asesoramiento y diseño de espacios interiores', TRUE)
ON CONFLICT (nombre) DO NOTHING;


-- Zonas: barrios de CABA y partidos del AMBA.
-- Sin esto la app no funciona: solicitud.id_zona es NOT NULL con FK a zona.
INSERT INTO zona (nombre, descripcion, activo) VALUES
    ('Agronomía', 'Barrio de CABA', TRUE),
    ('Almagro', 'Barrio de CABA', TRUE),
    ('Balvanera', 'Barrio de CABA', TRUE),
    ('Barracas', 'Barrio de CABA', TRUE),
    ('Belgrano', 'Barrio de CABA', TRUE),
    ('La Boca', 'Barrio de CABA', TRUE),
    ('Boedo', 'Barrio de CABA', TRUE),
    ('Caballito', 'Barrio de CABA', TRUE),
    ('Chacarita', 'Barrio de CABA', TRUE),
    ('Coghlan', 'Barrio de CABA', TRUE),
    ('Colegiales', 'Barrio de CABA', TRUE),
    ('Constitución', 'Barrio de CABA', TRUE),
    ('Flores', 'Barrio de CABA', TRUE),
    ('Floresta', 'Barrio de CABA', TRUE),
    ('Liniers', 'Barrio de CABA', TRUE),
    ('Mataderos', 'Barrio de CABA', TRUE),
    ('Monserrat', 'Barrio de CABA', TRUE),
    ('Monte Castro', 'Barrio de CABA', TRUE),
    ('Nueva Pompeya', 'Barrio de CABA', TRUE),
    ('Núñez', 'Barrio de CABA', TRUE),
    ('Palermo', 'Barrio de CABA', TRUE),
    ('Parque Avellaneda', 'Barrio de CABA', TRUE),
    ('Parque Chacabuco', 'Barrio de CABA', TRUE),
    ('Parque Chas', 'Barrio de CABA', TRUE),
    ('Parque Patricios', 'Barrio de CABA', TRUE),
    ('La Paternal', 'Barrio de CABA', TRUE),
    ('Puerto Madero', 'Barrio de CABA', TRUE),
    ('Recoleta', 'Barrio de CABA', TRUE),
    ('Retiro', 'Barrio de CABA', TRUE),
    ('Saavedra', 'Barrio de CABA', TRUE),
    ('San Cristóbal', 'Barrio de CABA', TRUE),
    ('San Nicolás', 'Barrio de CABA', TRUE),
    ('San Telmo', 'Barrio de CABA', TRUE),
    ('Vélez Sarsfield', 'Barrio de CABA', TRUE),
    ('Versalles', 'Barrio de CABA', TRUE),
    ('Villa Crespo', 'Barrio de CABA', TRUE),
    ('Villa del Parque', 'Barrio de CABA', TRUE),
    ('Villa Devoto', 'Barrio de CABA', TRUE),
    ('Villa General Mitre', 'Barrio de CABA', TRUE),
    ('Villa Lugano', 'Barrio de CABA', TRUE),
    ('Villa Luro', 'Barrio de CABA', TRUE),
    ('Villa Ortúzar', 'Barrio de CABA', TRUE),
    ('Villa Pueyrredón', 'Barrio de CABA', TRUE),
    ('Villa Real', 'Barrio de CABA', TRUE),
    ('Villa Riachuelo', 'Barrio de CABA', TRUE),
    ('Villa Santa Rita', 'Barrio de CABA', TRUE),
    ('Villa Soldati', 'Barrio de CABA', TRUE),
    ('Villa Urquiza', 'Barrio de CABA', TRUE),
    ('Almirante Brown', 'Municipio/partido del AMBA', TRUE),
    ('Avellaneda', 'Municipio/partido del AMBA', TRUE),
    ('Berazategui', 'Municipio/partido del AMBA', TRUE),
    ('Berisso', 'Municipio/partido del AMBA', TRUE),
    ('Brandsen', 'Municipio/partido del AMBA', TRUE),
    ('Campana', 'Municipio/partido del AMBA', TRUE),
    ('Cañuelas', 'Municipio/partido del AMBA', TRUE),
    ('Ensenada', 'Municipio/partido del AMBA', TRUE),
    ('Escobar', 'Municipio/partido del AMBA', TRUE),
    ('Esteban Echeverría', 'Municipio/partido del AMBA', TRUE),
    ('Exaltación de la Cruz', 'Municipio/partido del AMBA', TRUE),
    ('Ezeiza', 'Municipio/partido del AMBA', TRUE),
    ('Florencio Varela', 'Municipio/partido del AMBA', TRUE),
    ('General Las Heras', 'Municipio/partido del AMBA', TRUE),
    ('General Rodríguez', 'Municipio/partido del AMBA', TRUE),
    ('General San Martín', 'Municipio/partido del AMBA', TRUE),
    ('Hurlingham', 'Municipio/partido del AMBA', TRUE),
    ('Ituzaingó', 'Municipio/partido del AMBA', TRUE),
    ('José C. Paz', 'Municipio/partido del AMBA', TRUE),
    ('La Matanza', 'Municipio/partido del AMBA', TRUE),
    ('La Plata', 'Municipio/partido del AMBA', TRUE),
    ('Lanús', 'Municipio/partido del AMBA', TRUE),
    ('Lomas de Zamora', 'Municipio/partido del AMBA', TRUE),
    ('Luján', 'Municipio/partido del AMBA', TRUE),
    ('Malvinas Argentinas', 'Municipio/partido del AMBA', TRUE),
    ('Marcos Paz', 'Municipio/partido del AMBA', TRUE),
    ('Merlo', 'Municipio/partido del AMBA', TRUE),
    ('Moreno', 'Municipio/partido del AMBA', TRUE),
    ('Morón', 'Municipio/partido del AMBA', TRUE),
    ('Pilar', 'Municipio/partido del AMBA', TRUE),
    ('Presidente Perón', 'Municipio/partido del AMBA', TRUE),
    ('Quilmes', 'Municipio/partido del AMBA', TRUE),
    ('San Fernando', 'Municipio/partido del AMBA', TRUE),
    ('San Isidro', 'Municipio/partido del AMBA', TRUE),
    ('San Miguel', 'Municipio/partido del AMBA', TRUE),
    ('San Vicente', 'Municipio/partido del AMBA', TRUE),
    ('Tigre', 'Municipio/partido del AMBA', TRUE),
    ('Tres de Febrero', 'Municipio/partido del AMBA', TRUE),
    ('Vicente López', 'Municipio/partido del AMBA', TRUE),
    ('Zárate', 'Municipio/partido del AMBA', TRUE)
ON CONFLICT (nombre) DO NOTHING;
